import { useRef, useEffect } from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Profile from '../components/Profile';
import Summary from '../components/Summary';
import Education from '../components/Education';
import Work from '../components/Work';
import Contact from '../components/Contact';
import styles from '../styles/sections.module.css';

export default function Home() {
    const sections = {
        profile: useRef(null),
        summary: useRef(null),
        education: useRef(null),
        work: useRef(null),
        contact: useRef(null),
    };

    useEffect(() => {
        const handleScroll = () => {
            const scrollPosition = window.scrollY;
            const windowHeight = window.innerHeight;

            for (const sectionName in sections) {
                const section = sections[sectionName].current;
                if (section) {
                    const sectionTop = section.offsetTop;
                    const sectionHeight = section.offsetHeight;

                    if (scrollPosition >= sectionTop - windowHeight / 3 && scrollPosition < sectionTop + sectionHeight - windowHeight / 3) {
                        // Elimina la clase 'active' de todos los enlaces
                        document.querySelectorAll(`.${styles['navbar-link']}`).forEach(link => link.classList.remove(styles.active));

                        // Encuentra el enlace correspondiente a la sección actual y añade la clase 'active'
                        const activeLink = document.querySelector(`a[href="/#${sectionName}"]`);
                        if (activeLink) {
                            activeLink.classList.add(styles.active);
                        }
                        break;
                    }
                }
            }
        };

        window.addEventListener('scroll', handleScroll);
        handleScroll();
        return () => window.removeEventListener('scroll', handleScroll);
    }, [styles]); // Se añade styles como dependencia

    return (
        <>
            <Head>
                <title>Mi Portafolio</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Navbar /> {/* Se elimina el prop onClick */}
            <main>
                <section ref={sections.profile} id="profile" className={styles.section}>
                    <Profile />
                </section>
                <section ref={sections.summary} id="summary" className={styles.section}>
                    <Summary />
                </section>
                <section ref={sections.education} id="education" className={styles.section}>
                    <Education />
                </section>
                <section ref={sections.work} id="work" className={styles.section}>
                    <Work />
                </section>
                <section ref={sections.contact} id="contact" className={styles.section}>
                    <Contact />
                </section>
            </main>
            <Footer />
        </>
    );
}