import { useRef } from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Profile from '../components/Profile';
import Summary from '../components/Summary';
import Education from '../components/Education';
import Work from '../components/Work';
import Contact from '../components/Contact';

export default function Home() {
  const sections = {
    profile: useRef(null),
    summary: useRef(null),
    education: useRef(null),
    work: useRef(null),
    contact: useRef(null),
  };

  const handleClick = (section) => {
    sections[section].current?.scrollIntoView({ behavior: 'smooth' });
      // Espera a que el scroll termine antes de actualizar la clase active.
      setTimeout(() => {
        const sectionElements = Object.values(sections).filter(ref => ref.current);
          sectionElements.forEach(otherSection => {
              if (otherSection.current) {
                  otherSection.current.classList.remove('active');
              }
          });
          sections[section].current.classList.add('active');
      }, 500); // Ajusta este valor si el scroll suave es más lento o rápido
  };

  const sectionStyles = {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
    position: 'relative',
  };

  return (
    <>
      <Head>
        <title>Mi Portafolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar onClick={handleClick} />
      <main>
        <section ref={sections.profile} style={sectionStyles}>
          <Profile />
        </section>
        <section ref={sections.summary} style={sectionStyles}>
          <Summary />
        </section>
        <section ref={sections.education} style={sectionStyles}>
          <Education />
        </section>
        <section ref={sections.work} style={sectionStyles}>
          <Work />
        </section>
        <section ref={sections.contact} style={sectionStyles}>
          <Contact />
        </section>
      </main>
      <Footer />
    </>
  );
}